In [1]:
import pandas as pd
import numpy as np

In [3]:
data_preprocessed=pd.read_csv('Absenteeism_preprocessed.csv')

In [5]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_Values  Day_of_the_Week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

# Creating the Target

In [9]:
targets=np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [10]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [11]:
data_preprocessed['Excessive Absenteeism']=targets

In [12]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_Values  Day_of_the_Week  \
0         0         0         0         1             7                1   
1         0         0         0         0             7                1   
2         0         0         0         1             7                2   
3         1         0         0         0             7                3   
4         0         0         0         1             7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [91]:
data_with_targets=data_preprocessed.drop(['Absenteeism Time in Hours','Day_of_the_Week','Daily Work Load Average','Distance to Work'],axis=1)

In [94]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month_Values  \
0         0         0         0         1             7   
1         0         0         0         0             7   
2         0         0         0         1             7   
3         1         0         0         0             7   
4         0         0         0         1             7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

# Selecting the inputs for the Regression

In [95]:
data_with_targets.shape

(700, 12)

In [96]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month_Values  \
0           0         0         0         1             7   
1           0         0         0         0             7   
2           0         0         0         1             7   
3           1         0         0         0             7   
4           0         0         0         1             7   
..        ...       ...       ...       ...           ...   
695         1         0         0         0             5   
696         1         0         0         0             5   
697         1         0         0         0             5   
698         0         0         0         1             5   
699         0         0         0         1             5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [97]:
unscaled_inputs=data_with_targets.iloc[:,:-1]

# Standardizing the data

In [98]:
from sklearn.preprocessing import StandardScaler
absenteesim_scaler=StandardScaler()

In [99]:
absenteesim_scaler.fit(unscaled_inputs)

StandardScaler()

In [100]:
scaled_inputs=absenteesim_scaler.transform(unscaled_inputs)

In [101]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [102]:
scaled_inputs.shape

(700, 11)

# Splitting the data into train and test data

In [103]:
from sklearn.model_selection import train_test_split

In [104]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)

In [105]:
print(x_train.shape,y_train.shape)

(560, 11) (560,)


In [106]:
print(x_test.shape,y_test.shape)

(140, 11) (140,)


# Logistic Regression with sklearn

In [107]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [108]:
reg=LogisticRegression()

In [109]:
reg.fit(x_train,y_train)

LogisticRegression()

In [110]:
reg.score(x_train,y_train)

0.7857142857142857

# Manually Checking the Accuracy

In [111]:
model_outputs=reg.predict(x_train)

In [112]:
model_outputs

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [113]:
y_train


array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [114]:
model_outputs==y_train


array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [115]:
np.sum(model_outputs==y_train)

440

In [116]:
accuracy_manual=np.sum(model_outputs==y_train)/model_outputs.shape[0]
accuracy_manual

0.7857142857142857

In [117]:
accuracy_manual==reg.score(x_train,y_train) #The manually calculated accuracy is same as the accuracy predicted by applying algorithm

True

# Finding the intercept and the coefficient

In [118]:
reg.intercept_

array([-0.21783203])

In [119]:
reg.coef_

array([[ 2.05335916,  0.3294394 ,  1.55190184,  1.29507765,  0.01972353,
         0.71354973, -0.20234414,  0.33178109, -0.13964122,  0.37829975,
        -0.31915632]])

In [120]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month_Values',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [121]:
feature_name=unscaled_inputs.columns.values

In [122]:
summary_table=pd.DataFrame(columns=['Feature Name'],data=feature_name)

summary_table['Coefficient']=np.transpose(reg.coef_)

summary_table

Feature Name  Coefficient
0                 Reason_1     2.053359
1                 Reason_2     0.329439
2                 Reason_3     1.551902
3                 Reason_4     1.295078
4             Month_Values     0.019724
5   Transportation Expense     0.713550
6                      Age    -0.202344
7          Body Mass Index     0.331781
8                Education    -0.139641
9                 Children     0.378300
10                    Pets    -0.319156

In [77]:
summary_table.index=summary_table.index+1

summary_table.loc[0]=['Intercept',reg.intercept_[0]]

summary_table=summary_table.sort_index()

summary_table

Feature Name  Coefficient
0                 Intercept    -0.211509
1                  Reason_1     2.071923
2                  Reason_2     0.330750
3                  Reason_3     1.563900
4                  Reason_4     1.312837
5              Month_Values     0.025773
6           Day_of_the_Week    -0.086228
7    Transportation Expense     0.723270
8          Distance to Work    -0.061490
9                       Age    -0.206283
10  Daily Work Load Average    -0.028656
11          Body Mass Index     0.325900
12                Education    -0.161417
13                 Children     0.381534
14                     Pets    -0.321298

In [123]:
summary_table['Odds_Ratio']=np.exp(summary_table.Coefficient)
summary_table

Feature Name  Coefficient  Odds_Ratio
0                 Reason_1     2.053359    7.794039
1                 Reason_2     0.329439    1.390189
2                 Reason_3     1.551902    4.720439
3                 Reason_4     1.295078    3.651279
4             Month_Values     0.019724    1.019919
5   Transportation Expense     0.713550    2.041224
6                      Age    -0.202344    0.816814
7          Body Mass Index     0.331781    1.393448
8                Education    -0.139641    0.869670
9                 Children     0.378300    1.459800
10                    Pets    -0.319156    0.726762

In [125]:
summary_table.sort_values('Odds_Ratio',ascending=False)

Feature Name  Coefficient  Odds_Ratio
0                 Reason_1     2.053359    7.794039
2                 Reason_3     1.551902    4.720439
3                 Reason_4     1.295078    3.651279
5   Transportation Expense     0.713550    2.041224
9                 Children     0.378300    1.459800
7          Body Mass Index     0.331781    1.393448
1                 Reason_2     0.329439    1.390189
4             Month_Values     0.019724    1.019919
8                Education    -0.139641    0.869670
6                      Age    -0.202344    0.816814
10                    Pets    -0.319156    0.726762

# Testing the Model

In [127]:
reg.score(x_test,y_test)

0.7285714285714285

In [128]:
predicted_proba=reg.predict_proba(x_test)
predicted_proba

array([[0.75421642, 0.24578358],
       [0.59539901, 0.40460099],
       [0.44630818, 0.55369182],
       [0.76179858, 0.23820142],
       [0.06688666, 0.93311334],
       [0.28110343, 0.71889657],
       [0.29033427, 0.70966573],
       [0.07123589, 0.92876411],
       [0.74646516, 0.25353484],
       [0.75748572, 0.24251428],
       [0.47932748, 0.52067252],
       [0.15449041, 0.84550959],
       [0.03562045, 0.96437955],
       [0.72941793, 0.27058207],
       [0.22637795, 0.77362205],
       [0.50950602, 0.49049398],
       [0.47785384, 0.52214616],
       [0.48522536, 0.51477464],
       [0.3649302 , 0.6350698 ],
       [0.03406205, 0.96593795],
       [0.74196871, 0.25803129],
       [0.76179858, 0.23820142],
       [0.47417247, 0.52582753],
       [0.46828672, 0.53171328],
       [0.15646744, 0.84353256],
       [0.74758115, 0.25241885],
       [0.48984716, 0.51015284],
       [0.89932934, 0.10067066],
       [0.16200698, 0.83799302],
       [0.76179858, 0.23820142],
       [0.

In [129]:
predicted_proba[:,1]

array([0.24578358, 0.40460099, 0.55369182, 0.23820142, 0.93311334,
       0.71889657, 0.70966573, 0.92876411, 0.25353484, 0.24251428,
       0.52067252, 0.84550959, 0.96437955, 0.27058207, 0.77362205,
       0.49049398, 0.52214616, 0.51477464, 0.6350698 , 0.96593795,
       0.25803129, 0.23820142, 0.52582753, 0.53171328, 0.84353256,
       0.25241885, 0.51015284, 0.10067066, 0.83799302, 0.23820142,
       0.39892366, 0.73068312, 0.72717417, 0.5236194 , 0.23820142,
       0.63705422, 0.25465409, 0.84717757, 0.45536312, 0.63040781,
       0.23713148, 0.4720651 , 0.25019664, 0.10846639, 0.83596589,
       0.68657518, 0.73498601, 0.24035124, 0.24614431, 0.23606486,
       0.48385234, 0.06568907, 0.71889657, 0.24070655, 0.8475134 ,
       0.40744936, 0.94698798, 0.25210878, 0.08041796, 0.08085575,
       0.71131672, 0.72246279, 0.2554638 , 0.84739027, 0.23430186,
       0.24469052, 0.01194729, 0.25577658, 0.83905596, 0.27526937,
       0.24798751, 0.07814175, 0.91076928, 0.45243554, 0.63157

# Save the model

In [130]:
import pickle

In [132]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [135]:
with open('scaler','wb') as file:
    pickle.dump(absenteesim_scaler,file)